### ISSUE TITLE
Chat isn't working as of now

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/server#46]
I can login to development server with latest android app but can't enter or create a room. @nechaido @belochub @lidaamber

**Comment by lundibundi** [comment]
The server has recently been updated to use the new version of jstp 1.0, but jstp-java currently used in the Android app is not compatible with it. This is already fixed in new version of jstp-java but the Android app is yet to be updated as there were a few breaking changes and the version is not entirely compatible. But we have agreed with @lidaamber to update to the newest version right away because she also wanted to refactor a few things of her own in the Android app besides jstp and it will also allow to simplify a few things in jstp-related parts of the app. Though, I can release a patch for the version currently used in the Android app (just a patch version to that one) if it's needed.

**Comment by tshemsedinov** [comment]
@lundibundi thanks, we need this to show at presentation next week
